<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="Test"
           tests="5"
           failures="4"
           errors="0"
           skipped="0"
           time="3.019">
  <properties />
            <testcase name="f" time="0.223" classname="com.qingzi.test.ApiTest_qz">
                <failure type="java.lang.AssertionError"
                  message="expected [,,] but found [{&quot;data&quot;:&quot;success&quot;,&quot;code&quot;:200,&quot;message&quot;:&quot;success&quot;}]"
              >
<![CDATA[java.lang.AssertionError: expected [,,] but found [{"data":"success","code":200,"message":"success"}]
  org.testng.Assert.fail(Assert.java:94)
  org.testng.Assert.failNotEquals(Assert.java:494)
  org.testng.Assert.assertEquals(Assert.java:123)
  org.testng.Assert.assertEquals(Assert.java:176)
  org.testng.Assert.assertEquals(Assert.java:186)
  com.qingzi.test.ApiTest_qz.f(ApiTest_qz.java:95)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.lang.reflect.Method.invoke(Method.java:498)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
  org.testng.TestRunner.privateRun(TestRunner.java:767)
  org.testng.TestRunner.run(TestRunner.java:617)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:335)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:330)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
  org.testng.SuiteRunner.run(SuiteRunner.java:240)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
  org.testng.TestNG.run(TestNG.java:1057)
  org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:73)
  org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
]]>
      </failure>

          </testcase>
            <testcase name="f" time="0.158" classname="com.qingzi.test.ApiTest_qz">
                <failure type="java.lang.AssertionError"
                  message="expected [,,] but found [{&quot;data&quot;:{&quot;id&quot;:&quot;1-EP-98937751641333760&quot;},&quot;code&quot;:200,&quot;message&quot;:&quot;success&quot;}]"
              >
<![CDATA[java.lang.AssertionError: expected [,,] but found [{"data":{"id":"1-EP-98937751641333760"},"code":200,"message":"success"}]
  org.testng.Assert.fail(Assert.java:94)
  org.testng.Assert.failNotEquals(Assert.java:494)
  org.testng.Assert.assertEquals(Assert.java:123)
  org.testng.Assert.assertEquals(Assert.java:176)
  org.testng.Assert.assertEquals(Assert.java:186)
  com.qingzi.test.ApiTest_qz.f(ApiTest_qz.java:95)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.lang.reflect.Method.invoke(Method.java:498)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
  org.testng.TestRunner.privateRun(TestRunner.java:767)
  org.testng.TestRunner.run(TestRunner.java:617)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:335)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:330)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
  org.testng.SuiteRunner.run(SuiteRunner.java:240)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
  org.testng.TestNG.run(TestNG.java:1057)
  org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:73)
  org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
]]>
      </failure>

          </testcase>
            <testcase name="f" time="2.224" classname="com.qingzi.test.ApiTest_qz">
                <failure type="java.lang.AssertionError"
                  message="expected [,,] but found [{&quot;code&quot;:200,&quot;message&quot;:&quot;success&quot;,&quot;data&quot;:{&quot;tls_addr&quot;:&quot;192.168.201.194:8091&quot;,&quot;ttl&quot;:1635414343637,&quot;create_time&quot;:1632822343633,&quot;s_UserToken&quot;:&quot;e1eca8906f90448cd2fc1125798aaa5c&quot;,&quot;MRId&quot;:&quot;1-MR-98581227756552192&quot;,&quot;mId&quot;:&quot;112372209&quot;,&quot;accountId&quot;:&quot;CN-86-1-UA-98581227710521344&quot;}}]"
              >
<![CDATA[java.lang.AssertionError: expected [,,] but found [{"code":200,"message":"success","data":{"tls_addr":"192.168.201.194:8091","ttl":1635414343637,"create_time":1632822343633,"s_UserToken":"e1eca8906f90448cd2fc1125798aaa5c","MRId":"1-MR-98581227756552192","mId":"112372209","accountId":"CN-86-1-UA-98581227710521344"}}]
  org.testng.Assert.fail(Assert.java:94)
  org.testng.Assert.failNotEquals(Assert.java:494)
  org.testng.Assert.assertEquals(Assert.java:123)
  org.testng.Assert.assertEquals(Assert.java:176)
  org.testng.Assert.assertEquals(Assert.java:186)
  com.qingzi.test.ApiTest_qz.f(ApiTest_qz.java:95)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.lang.reflect.Method.invoke(Method.java:498)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
  org.testng.TestRunner.privateRun(TestRunner.java:767)
  org.testng.TestRunner.run(TestRunner.java:617)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:335)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:330)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
  org.testng.SuiteRunner.run(SuiteRunner.java:240)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
  org.testng.TestNG.run(TestNG.java:1057)
  org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:73)
  org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
]]>
      </failure>

          </testcase>
            <testcase name="f" time="0.255" classname="com.qingzi.test.ApiTest_qz">
                <failure type="java.lang.AssertionError"
                  message="expected [,,] but found [{&quot;data&quot;:{&quot;meetingId&quot;:&quot;1-M-98937603412500480&quot;},&quot;code&quot;:50007,&quot;message&quot;:&quot;MeetingExistException:can not join a another meeting!&quot;}]"
              >
<![CDATA[java.lang.AssertionError: expected [,,] but found [{"data":{"meetingId":"1-M-98937603412500480"},"code":50007,"message":"MeetingExistException:can not join a another meeting!"}]
  org.testng.Assert.fail(Assert.java:94)
  org.testng.Assert.failNotEquals(Assert.java:494)
  org.testng.Assert.assertEquals(Assert.java:123)
  org.testng.Assert.assertEquals(Assert.java:176)
  org.testng.Assert.assertEquals(Assert.java:186)
  com.qingzi.test.ApiTest_qz.f(ApiTest_qz.java:95)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.lang.reflect.Method.invoke(Method.java:498)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
  org.testng.TestRunner.privateRun(TestRunner.java:767)
  org.testng.TestRunner.run(TestRunner.java:617)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:335)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:330)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
  org.testng.SuiteRunner.run(SuiteRunner.java:240)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
  org.testng.TestNG.run(TestNG.java:1057)
  org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:73)
  org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
]]>
      </failure>

          </testcase>
  
  
            <testcase name="f" time="0.159" classname="com.qingzi.test.ApiTest_qz" />
      
</testsuite>
